import React from "react";
import { AgentInfo } from "../types";
import { Info } from "lucide-react";

interface AgentOrchestrationProps {
  agents: AgentInfo[];
  agentStates: Record<string, "queued" | "running" | "done" | "gate">;
  agentTimes: Record<string, string>;
  occasionQuote: string;
  occasionScores: string[];
  logs: string[];
  onSelectAgent: (agent: AgentInfo) => void;
}

export const AgentOrchestration: React.FC<AgentOrchestrationProps> = ({
  agents,
  agentStates,
  agentTimes,
  occasionQuote,
  occasionScores,
  logs,
  onSelectAgent,
}) => {
  return (
    <div id="agent-orchestration-panel" className="panel bg-slate-900/40 rounded-3xl border border-slate-800 p-5 flex flex-col justify-between shadow-xl col-span-1 lg:col-span-5 h-full w-full overflow-hidden">
      <div>
        <div id="agent-orchestration-header" className="ph flex items-center justify-between text-xs font-semibold uppercase tracking-wider text-slate-400 mb-3">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-orange-500"></span>
            Agent orchestration
          </div>
          <em className="not-italic text-[10px] text-slate-500 font-mono">LangGraph · 8 agents · taste + demand</em>
        </div>

        {/* Agents List */}
        <div id="agents-grid-container" className="flex flex-col gap-1.5">
          {agents.map((a) => {
            const st = agentStates[a.id] || "queued";
            const timeVal = agentTimes[a.id] || "queued";

            let stateClass = "border-slate-800/80 bg-slate-800/30";
            let aidClass = "bg-slate-800 text-slate-400";

            if (st === "running") {
              stateClass = "border-orange-500 bg-orange-500/10 shadow-[0_0_12px_rgba(249,115,22,0.15)]";
              aidClass = "bg-orange-500 text-slate-950 font-bold";
            } else if (st === "done") {
              stateClass = "border-green-500/30 bg-green-500/5";
              aidClass = "bg-green-500 text-slate-950 font-bold";
            } else if (st === "gate") {
              stateClass = "border-orange-500/80 bg-orange-500/20 shadow-[0_0_14px_rgba(249,115,22,0.2)]";
              aidClass = "bg-amber-400 text-slate-950 font-bold";
            }

            return (
              <div
                key={a.id}
                id={`agent-row-${a.id}`}
                onClick={() => onSelectAgent(a)}
                className={`agent grid grid-cols-[26px_1fr_auto] gap-2.5 items-center px-3 py-2 rounded-xl border transition-all cursor-pointer hover:border-orange-500/40 group ${stateClass}`}
              >
                <div className={`aid w-6 h-6 rounded-lg flex items-center justify-center text-[10px] font-extrabold font-mono transition-colors ${aidClass}`}>
                  {a.id}
                </div>
                <div>
                  <div className="an text-[12px] font-bold text-white flex items-center gap-1.5">
                    {a.n}
                    <Info className="w-3 h-3 text-slate-500 opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                  <div className="ad text-[9.5px] text-slate-400 leading-tight">{a.d}</div>
                </div>
                <div className={`at font-mono text-[9.5px] text-right min-w-[48px] ${st === "done" ? "text-green-400" : "text-slate-400"}`}>
                  {timeVal}
                </div>
              </div>
            );
          })}
        </div>

        {/* Occasion Card auto-generated by ARBITER */}
        <div
          id="occasion-card-container"
          className={`opp border border-orange-500/30 rounded-2xl p-3.5 mt-3 bg-gradient-to-br from-orange-600/10 to-orange-800/10 transition-all duration-500 ${
            occasionQuote !== "—" ? "opacity-100" : "opacity-40"
          }`}
        >
          <h4 className="text-[10px] tracking-[0.15em] text-orange-400 uppercase font-bold mb-1.5">
            Occasion card · auto-generated by ARBITER
          </h4>
          <div className="q text-[13px] font-bold leading-snug text-white mb-2.5">{occasionQuote}</div>
          <div className="scores grid grid-cols-4 gap-2">
            <div className="text-center border border-slate-800 rounded-xl p-1.5 bg-slate-900/80">
              <b className="block font-mono text-[15px] text-orange-400">{occasionScores[0]}</b>
              <span className="text-[7px] text-slate-400 tracking-wider uppercase">Occasion fit</span>
            </div>
            <div className="text-center border border-slate-800 rounded-xl p-1.5 bg-slate-900/80">
              <b className="block font-mono text-[15px] text-orange-400">{occasionScores[1]}</b>
              <span className="text-[7px] text-slate-400 tracking-wider uppercase">Velocity</span>
            </div>
            <div className="text-center border border-slate-800 rounded-xl p-1.5 bg-slate-900/80">
              <b className="block font-mono text-[15px] text-orange-400">{occasionScores[2]}</b>
              <span className="text-[7px] text-slate-400 tracking-wider uppercase">Risk</span>
            </div>
            <div className="text-center border border-slate-800 rounded-xl p-1.5 bg-slate-900/80">
              <b className="block font-mono text-[15px] text-orange-400">{occasionScores[3]}</b>
              <span className="text-[7px] text-slate-400 tracking-wider uppercase">Headroom ₹cr</span>
            </div>
          </div>
        </div>
      </div>

      {/* Execution Log Terminal */}
      <div
        id="execution-log-terminal"
        className="log mt-3 h-[92px] overflow-y-auto border border-slate-800 pt-2 font-mono text-[9.5px] leading-relaxed text-slate-300 bg-slate-950/80 px-3 rounded-2xl"
      >
        {logs.map((line, idx) => (
          <div key={idx} dangerouslySetInnerHTML={{ __html: line }} />
        ))}
      </div>
    </div>
  );
};
